apiVersion: argoproj.io/v1alpha1
kind: EventSource
metadata:
  name: amqp
spec:
  amqp:
    fission-workflow:
      # amqp server url - local
      url: amqp://rabbitmq-service.default:5672
      # jsonBody specifies that all event body payload coming from this
      # source will be JSON
      jsonBody: true
      # name of the exchange.
      exchangeName: fission-workflow
      # exchange type. more info at https://www.rabbitmq.com/tutorials/amqp-concepts.html#exchanges
      exchangeType: fanout
      # routing key
      routingKey: fission
      # optional backoff time for connection retries.
      # if not provided, default connection backoff time will be used.
      connectionBackoff:
        # duration in nanoseconds, or strings like "1s", "1m". following value is 10 seconds
        duration: 10s
        # how many backoffs
        steps: 5
        # factor to increase on each step.
        # setting factor > 1 makes backoff exponential.
        factor: 2
        jitter: 0.2
      # optional exchange settings
      # if not provided, default values will be used
      exchangeDeclare:
        durable: true
        autoDelete: false
        internal: false
        noWait: false
      # optional queue settings
      # if not provided, default values will be used
      queueDeclare:
        name: "fission-workflow-queue"
        durable: false
        autoDelete: false
        exclusive: true
        noWait: false
      # optional queue binding settings
      # if not provided, default values will be used
      queueBind:
        noWait: false
      # optional consume settings
      # if not provided, default values will be used
      consume:
        consumerTag: "my-consumer-tag"
        autoAck: true
        exclusive: false
        noLocal: false
        noWait: false